(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function c(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(t){if(t.ep)return;t.ep=!0;const n=c(t);fetch(t.href,n)}})();new Swiper(".swiper-container",{slidesPerView:5,spaceBetween:0,loop:!0,navigation:{nextEl:".swiper-button-next"},keyboard:{enabled:!0}});document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".container-button-next").forEach(e=>{e.addEventListener("click",function(c){c.preventDefault();const o=document.querySelector(".target-text");o.classList.contains("hidden")?(o.classList.remove("hidden"),o.classList.add("visible")):(o.classList.remove("visible"),o.classList.add("hidden")),console.log("Button clicked")})})});document.addEventListener("DOMContentLoaded",function(){document.getElementById("order-button").addEventListener("click",function(){document.getElementById("work-together").scrollIntoView({behavior:"smooth",block:"start"})})});document.querySelector(".cover-container");const v=document.querySelector(".cover-section"),p=document.querySelectorAll(".cover"),h=new IntersectionObserver(r=>{r.forEach(e=>{e.isIntersecting?p.forEach(c=>c.style.animationPlayState="running"):p.forEach(c=>c.style.animationPlayState="paused")})});h.observe(v);document.addEventListener("DOMContentLoaded",function(){const r=document.querySelector(".container-form form"),e=document.querySelector(".modal-footer"),c=document.querySelector(".close");r.addEventListener("submit",function(o){o.preventDefault(),e.style.display="block",document.body.style.overflow="hidden";const t=new FormData(r);fetch("submit.php",{method:"POST",body:t}).then(n=>{n.ok?(e.style.display="flex",r.reset()):alert("Error sending request. Try again.")}).catch(n=>{alert("Something went wrong. Please try again.")})}),c.addEventListener("click",function(){e.style.display="none",document.body.style.overflow=""}),window.addEventListener("click",function(o){o.target===e&&(e.style.display="none")})});document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector(".logo-container-header"),e=document.querySelector(".ankors-menu"),c=document.querySelector(".menu-div");if(!r){console.error("Элемент с классом '.logo-container-header' не найден!");return}const o=["About me","Benefits","Projects","FAQ"],t=i=>`
        <li class='acnkorLink'>
            <a href='#'>${i}</a>
        </li>
    `;(i=>e.insertAdjacentHTML("beforeend",i))((i=>i.map(u=>t(u)).join(""))(o));const y=(i,u)=>i.classList.toggle(u),b=()=>{y(e,"is-hidden")};c.addEventListener("click",b);const m=document.querySelector(".burger-whipe a"),a=document.querySelector(".menu"),f=document.querySelector(".close-btn");if(!m||!a||!f){console.error("Не найден один из элементов меню!");return}m.addEventListener("click",i=>{i.preventDefault(),a.style.display="block"}),f.addEventListener("click",()=>{a.style.display="none"})});const w=[{url:"https://www.instagram.com/goitclub/",text:"IG"},{url:"https://www.facebook.com/goITclub/",text:"FB"},{url:"https://www.youtube.com/c/GoIT",text:"YT"},{url:"https://github.com/Alex-chernomor/project-K3n5t13n",text:"GH"},{url:"mailto:lloydfefferson@gmail.com",text:"lloydfefferson@gmail.com",isEmail:!0}],E=document.querySelector(".list-link"),L=r=>r.map(e=>`
        <li class="link-wrap${e.isEmail?" link-big":""}">
            <a class="link" href="${e.url}" target="_blank">${e.text}</a>
        </li>
    `).join("");E.innerHTML=L(w);const d=[{url:"../img/imgJPEG/projectImg/projectImg2.jpg"},{url:"../img/imgJPEG/projectImg/projectImg3.jpg"}];let s=0;const k=document.getElementById("project-img"),S=document.querySelector(".button-project"),B=document.querySelector(".button-project-second");function g(){k.src=d[s].url}S.addEventListener("click",()=>{s=(s+1)%d.length,g()});B.addEventListener("click",()=>{s=(s-1+d.length)%d.length,g()});new Swiper(".swiper",{loop:!1,navigation:{nextEl:".button-project",prevEl:".button-project-second"},keyboard:{enabled:!0}});new Swiper(".container-reviews",{slidesPerView:4,spaceBetween:16,loop:!1,navigation:{nextEl:".button-round",prevEl:".button-round-second"},keyboard:{enabled:!0},on:{init:function(){prevButton.disabled=this.isBeginning,nextButton.disabled=this.isEnd},slideChange:function(){prevButton.disabled=this.isBeginning,nextButton.disabled=this.isEnd}}});
//# sourceMappingURL=index.js.map
